/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dfe5d5",
        "on-secondary-fixed-variant": "#01530d",
        "secondary": "#246c24",
        "surface-dim": "#d7dccd",
        "surface-tint": "#2d6c00",
        "on-tertiary-fixed": "#181e00",
        "on-surface-variant": "#404a39",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#3f4c00",
        "surface-bright": "#f6fbec",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#707a67",
        "tertiary-container": "#697d00",
        "on-secondary-fixed": "#002202",
        "on-error-container": "#93000a",
        "tertiary": "#536200",
        "secondary-fixed-dim": "#8dd983",
        "on-secondary-container": "#297128",
        "primary-container": "#398500",
        "inverse-primary": "#86dc53",
        "on-background": "#181d14",
        "on-primary-fixed-variant": "#205100",
        "tertiary-fixed-dim": "#b4d400",
        "on-primary": "#ffffff",
        "surface": "#f6fbec",
        "surface-container": "#ebf0e0",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#fcffe1",
        "error": "#ba1a1a",
        "secondary-container": "#a5f39a",
        "on-surface": "#181d14",
        "primary-fixed": "#a1f96c",
        "on-primary-fixed": "#092100",
        "tertiary-fixed": "#d0f130",
        "secondary-fixed": "#a8f59c",
        "outline-variant": "#c0cab4",
        "surface-container-low": "#f0f6e6",
        "surface-variant": "#dfe5d5",
        "inverse-on-surface": "#edf3e3",
        "primary": "#2c6900",
        "on-primary-container": "#f8ffed",
        "primary-fixed-dim": "#86dc53",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3228",
        "background": "#f6fbec",
        "surface-container-high": "#e5eadb",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "container-margin": "24px",
        "unit": "8px",
        "touch-target-min": "56px",
        "gutter": "16px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "30px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      animation: {
        "spin-slow": "spin 3s linear infinite",
      },
    },
  },
  plugins: [],
}
